settings:
  overall:
    symbol: XAUUSD
    magic:  101011

  connection:
    token: 3344c48d1371d9c5106d8ea5a3ccf44d5c70dbf1

  martingale:
    enable: False
    level_spacing: 50
    scale_factor: 2
    level_maximum: 5
    total_profit: 5

  money-management:
    initial_volume: 0.1
    stop_loss: 100
    take_profit: 1000

  trailing:
    enable_trailing: True
    trailing_start: 50
    trailing_step: 5

  signals:
    open_type: EMA_RSI
    close_type: EMA
    time_frame: m1
    number_of_candles: 300
    ema:
      fast_sma_periods: 25
      slow_sma_periods: 50
      fast_sma_shift: 0
      slow_sma_shift: 0
    rsi:
      period: 7
      max: 70
      min: 30
  others: